# Generated by Django 4.2.1 on 2023-05-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='upload/images/projects/')),
                ('impact', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('issue', models.TextField(max_length=300)),
                ('method', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='howwedo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='upload/images/whatwedo/howwedo/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
