# Generated by Django 4.2.1 on 2023-05-12 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('whatwedo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lang_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
            preserve_default=False,
        ),
    ]
