# Generated by Django 4.2.1 on 2023-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0002_project_lang_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='button_name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='button_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='image_banner',
            field=models.ImageField(null=True, upload_to='upload/images/projects/'),
        ),
    ]
