# Generated by Django 4.2.1 on 2023-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0003_project_button_name_project_button_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='impact_name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
