# Generated by Django 4.2.1 on 2023-06-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0004_project_impact_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howwedo',
            options={'verbose_name_plural': 'How we do'},
        ),
    ]
