# Generated by Django 4.2.1 on 2023-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='short_name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
