# Generated by Django 4.2.1 on 2023-05-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy_policy',
            name='body',
            field=models.TextField(),
        ),
    ]
