# Generated by Django 4.2.1 on 2023-05-30 11:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_privacy_policy_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy_policy',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
