# Generated by Django 4.2.1 on 2023-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_alter_privacy_policy_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacy_policy',
            options={'verbose_name_plural': 'Privacy & Policies'},
        ),
        migrations.AddField(
            model_name='language',
            name='logo',
            field=models.ImageField(null=True, upload_to='upload/images/language/'),
        ),
    ]
