# Generated by Django 4.2 on 2023-04-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_partnership_opportunity', models.BooleanField()),
                ('message', models.CharField(max_length=2000)),
                ('last_name', models.TextField(max_length=100)),
                ('is_generail_inquiry', models.BooleanField()),
                ('phone', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.TextField(max_length=100)),
                ('is_training', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('helper', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
