# Generated by Django 4.2.1 on 2023-06-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Contact Informations'},
        ),
    ]
