version: "3.9"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0:9000
    volumes:
      - .:/ffngo
    ports:
      - 9000:9000
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: