# Generated by Django 4.2.1 on 2023-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoweare', '0002_alter_timeline_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='our_vision',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='whoweare',
            field=models.TextField(),
        ),
    ]
