# Generated by Django 4.2.1 on 2023-05-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoweare', '0003_alter_main_our_vision_alter_main_whoweare'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='upload/images/team/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('position', models.TextField(max_length=100)),
                ('country', models.TextField(max_length=100)),
            ],
        ),
    ]
