# Generated by Django 4.2.1 on 2023-05-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_privacy_policy_body'),
        ('whoweare', '0005_our_team_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_team',
            name='lang_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
    ]
