# Generated by Django 4.2.1 on 2023-06-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoweare', '0007_timeline_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_team',
            name='is_advisory_board',
            field=models.BooleanField(default=False),
        ),
    ]
