# Generated by Django 4.2.1 on 2023-06-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoweare', '0008_our_team_is_advisory_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name_plural': 'Main Informations'},
        ),
        migrations.AlterModelOptions(
            name='our_team',
            options={'verbose_name_plural': 'Our Team'},
        ),
    ]
