# Generated by Django 4.2.1 on 2023-06-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoweare', '0009_alter_main_options_alter_our_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
