version: "3.9"

services:
  db:
    container_name: ffngo_skeleton_db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=ffngo
      - POSTGRES_USER=ffngo
      - POSTGRES_PASSWORD=ffngo
  python:
    container_name: ffngo_skeleton_python
    build: 
      context: '../'
      dockerfile: './docker/prod/dockerfile'
    working_dir: /var/www/ffngo/code/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - '../:/var/www/ffngo'
      - /var/www/ffngo/media
    ports:
      - 8000:8000
    links:
      - db
    environment:
      VIRTUAL_HOST: farofoundation.org
      LETSENCRYPT_HOST: farofoundation.org
  nginx: 
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    build:
      context: '../'
      dockerfile: ./docker/nginx/dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
      - /home/ubuntu/ffmbknd/code/media:/var/www/ffngo/media
      - /home/ubuntu/ffmbknd/static:/var/www/ffngo/static
      - /home/ubuntu/ffmbknd/frontend:/var/www/frontend
    logging:
      options:
          max-size: "10m"
          max-file: "3"
    depends_on:
      - python
    environment:
    - NGINX_DOCKER_GEN_CONTAINER=docker-gen
  letsencrypt-companion:
      container_name: letsencrypt-companion
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: unless-stopped
      volumes_from:
          - nginx
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/docker/nginx/acme:/etc/acme.sh
      environment:
          DEFAULT_EMAIL: 03hangerel03@mail.com
volumes:
  static_volume: {}
  postgres_data:
    driver: local