version: "3.9"

services:
  db:
    container_name: inv_skeleton_db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=ffngo
      - POSTGRES_USER=ffngo
      - POSTGRES_PASSWORD=ffngo
  python:
    container_name: inv_skeleton_python
    build: 
      context: '../'
      dockerfile: './docker/dev/dockerfile'
    working_dir: /var/www/ffngo/code/
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - '../:/var/www/ffngo'
      - /var/www/ffngo/var
      - ../var/upload:/var/www/ffngo/var/upload
    ports:
      - 9000:9000
    depends_on:
      - db
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./docker/nginx/certbot/conf:/etc/letsencrypt
  #     - ./docker/nginx/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" 
  nginx: 
    restart: unless-stopped
    build:
      context: '../'
      dockerfile: ./docker/nginx/dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/backend/server/django_static
      # - ./docker/nginx/certbot/conf:/etc/letsencrypt
      # - ./docker/nginx/certbot/www:/var/www/certbot
    depends_on:
      - python

volumes:
  static_volume: {}
  postgres_data:
    driver: local

# networks:
#   default:
#     external:
#       name: letsencrypt