# The first stage
# Build React static files
FROM node:16.15.0 as build

# COPY ./admin/ /var/www/admin/
# WORKDIR /var/www/admin/code

# COPY ./admin/code/package.json ./

# RUN yarn install --network-timeout 10000000
# RUN yarn add react-app-rewired --network-timeout 100000
# COPY ./admin/code/ ./
# RUN yarn build

# The second stage
# Copy React static files and start nginx
FROM nginx:stable-alpine

# COPY --from=build /var/www/admin/code/build /usr/share/nginx/html
# COPY ./docker/nginx/production/default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]