FROM node:16.15.0 as build

COPY ./frontend/ /var/www/ffngo/frontend/
WORKDIR /var/www/ffngo/frontend/code

COPY ./frontend/code/package.json ./

FROM nginx:stable-alpine

COPY --from=build /var/www/ffngo/frontend/code/build /usr/share/nginx/html
COPY ./docker/nginx/production/default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]