# Pull base image
FROM python:3.10.2-slim-bullseye

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
COPY . /var/www/ffngo/
WORKDIR /var/www/ffngo/

# Copy requirements file
COPY docker/prod/requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy project files
COPY . .

# Collect static files
RUN python code/manage.py collectstatic --noinput

# Change ownership
RUN chown -R www-data: /var/www/ffngo/static
RUN chmod -R u+w /var/www/ffngo/static