# Pull base image
FROM python:3.10.2-slim-bullseye

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
COPY . /var/www/ffngo/
WORKDIR /var/www/ffngo/

# Install dependencies
COPY /docker/prod/requirements.txt /var/www/ffngo/
RUN pip install -r requirements.txt