# Generated by Django 4.2.1 on 2023-05-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
    ]
