# Generated by Django 4.2.1 on 2023-06-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_partner_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landing',
            options={'verbose_name_plural': 'Home Informations'},
        ),
    ]
